### ISSUE TITLE
speech error on windows 8.1

### ISSUE THREAD

**Issue by firezblade** [axcore/axmud#2] opened 2019-01-04 13:10 UTC
Hello, I play on legendsofkallisti.com:4000 using the preconfigured world. When I type ;speak hello, either a)window media player starts and play a horn sound or
b)error message and nothing happens

**Comment by axcore** [comment] 2019-01-08 14:15
I don't have a Windows 8 Box, so I installed Axmud on a Windows 7 Box, connected to Kallisti, and typed ';speak hello', which worked as expected.

I'm not sure what the problem is, but I'm guessing that the speech engine is not installed properly on your system. (The installation programme installs Axmud and the speech engine at the same time, but perhaps you deselected the speech engine by mistake.)

Here are some things you can try:
1. Install Axmud again (run the installation programme again)
2. Install the speech engine yourself. Here is the link:
http://espeak.sourceforge.net/download.html
3. Try running "Axmud (visually-impaired users)" rather than the normal Axmud. Can you hear any speech when it starts? (You will find both versions of Axmud in your Windows start menu.)
4. Show me the error message(s) you're seeing when you type ";speak hello"

**Comment by firezblade** [comment] 2019-01-10 06:13
I got speech working when I reinstalled espeak into the default program files directory. Previously espeak was installed into another custom path. 

How can I select another voice? I cannot get voice to switch from english_rp to english-us or en-us+f3 to work.

Thanks!

**Comment by axcore** [comment] 2019-01-10 10:32
If the voice doesn't work, the most likely reason is that the voice isn't installed on your system. I just installed espeak on a clean Windows box. It installed the following voices:

en_en+f2
en-us

When Axmud starts, you can use this command to change voices:

;config receive voice en-us

That changes the voice used for text received from the world. If you want to change the voice used by system messages, you would use this command:

;config system voice en-us

**Comment by firezblade** [comment] 2019-01-15 12:52
Hi, is the forums up and working? Otherwise can I continue to post my questions here? Thanks!

Next question is about automapper. The room title and exits are on the same line. For example, My House [ N S E W ] . This shows up on the automapper as box with four asterisks* for exits in the wrong direction. exit N is mapped to the northeast corner, S to the east corner, E to the southeast corner etc.

**Comment by axcore** [comment] 2019-01-20 11:37
Forums are open for business; post your problems wherever it's most convenient.

The new exit-handling code is broken. It should convert an exit like N to lower-case letters, but doesn't. The fix will be in the next release.

I tried to write some clever triggers as a workaround, but none of them work satisfactorily. The only immediate fix would be to edit the source code file /lib/Games/Axmud/Task.pm, replacing line 27090:

`$modString = $axmud::CLIENT->trimWhitespace($exitString, TRUE);`                

With this;

`$modString = lc($axmud::CLIENT->trimWhitespace($exitString, TRUE));`

**Comment by firezblade** [comment] 2019-01-27 06:07
Sometimes, after I double click to walk to another room in the automapper, the perl interpreter stopped working. Is there anyway for me to retreive any crash logs/errors? Thanks!

**Comment by axcore** [comment] 2019-01-29 09:37
If you're running Axmud on MS Windows, Perl errors should be visible in the black terminal window, as well as in Axmud's main window. If that's not the case, perhaps you can take a screenshot that shows your map, the main window and the terminal window.

You can write a logifle that shows errors, but it doesn't catch all Perl errors. First enable logging in general:

;log -l

Then enable the 'errors' logfile:

;log errors

The location of the logfile depends on how you installed Axmud. Use this command to find Axmud's data directory:

;listdatadirectory
;ldd

Logfiles are written to the 'logs' subdirectory.

**Comment by firezblade** [comment] 2019-02-03 11:13
![ss1](https://user-images.githubusercontent.com/34786942/52176559-5ea43e80-27ef-11e9-9b0d-e60942762214.png)
Attached screenshot. When I click debug, it opens visual studio; close, only the cmd is left open. Thanks!

**Comment by axcore** [comment] 2019-02-06 08:46
Ok, here are some things to try:

Turn off drag mode, before moving to a new room. (It's the blue 'Dr' button at the top of the automapper window.)

Next: type this command, which tests for errors in the map:

;testmodel

If you see any errors, copy the error message here, then type this command, which fixes some errors automatically:

;testmodel -f

Next: download and install the development version of Axmud. Perhaps your problem has already been fixed:

https://www.dropbox.com/s/djdsspe0ymd51jc/install-axmud-1.1.422.exe?dl=0

Next: send me a copy of the map, and I will test the map until I find the problem. From the automapper window, File > Save/export world model

You can send the file to me at lestrol123 at gmx.com

**Closed as completed** 2020-09-19 11:50 UTC
